# Generated by Django 4.2.2 on 2023-08-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0003_alter_hobby_options_hobby_catalog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', models.CharField(max_length=60, verbose_name='Вид группы')),
                ('compound', models.CharField(max_length=100, verbose_name='Состав')),
            ],
        ),
    ]
