# Generated by Django 4.2.2 on 2023-09-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0004_catalog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'verbose_name': 'Каталог', 'verbose_name_plural': 'Каталоги'},
        ),
        migrations.AddField(
            model_name='catalog',
            name='img',
            field=models.ImageField(default=2, upload_to='my_gallery/%Y', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
