# Generated by Django 4.2.2 on 2023-09-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0006_hobby_catalog_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='catalog_top',
            field=models.ManyToManyField(related_name='hobbys', to='hobby.catalog'),
        ),
    ]
